### ISSUE TITLE
更换五子棋博客托管平台 及 与主博客风格一致性

### ISSUE THREAD

**Issue by dudulism** [dudulism/dudulism.github.io#1]
目前Lofter不能满足一些需求，新博客希望有所改善。可以开始撸了，最重要的核心
- [ ] 目录
- [ ] 标签、分类系统（jekyll原生支持）
- [x] 支持markdown（jekyll原生支持）
- [ ] 专栏（某一系列的棋评专栏、学习专栏等）
- [ ] 主页设计（布局：主页设计、博文设计）
- [ ] 图片（不烦闷。虽然我知道下五子棋的对Web UI大多有较强的容忍力，不过活泼点也没错）
- [ ] 截图自动上传、自动引用（Alfred插件或者自己写）
## 专栏及设计
- http://www.zuojj.com/archives/category/series/deep-css

**Comment by dudulism** [comment]
最近受了刺激，对重写五子棋博客有了一些兴趣。

先说布局，我有一些定制化的需求，一般的三栏式布局应该是可以满足的，但是此外我还有一个”专栏“的需求，有时可能是一个系列的文章，希望能够放在一起。可以说是更深一级的嵌套吧。同时三栏布局有些需要优化的地方：
- 默认不显示三栏，但这样就没有办法选文章了
- 左边两栏其实是很distracting的，我就看个文章，40%的页面是没有用，而且还充满了信息，干扰更大
